EXP:
  DATASET: s3dis
  NAME: s3dis
  PRETRAIN_MODEL_PATH: ./work_dirs/pretrain_final/model.t7
  DATA_PATH: /home/jimmy15923/mnt/data/s3dis_coseg_radius_1x
MODEL:
  ALPHA: 30
  BG_GAMMA: 0.7
  FG_GAMMA: 0.7
  GROUP_SIZE: 7
  LAMDA: 1.0
  MUTUAL_ATTENTION: true
  N_BG: 256
  N_FG: 256
  OBJ_LOSS: true
  POINT_LOSS: true
  REPULSION: 1.0
  REPUL_LOSS: true
  SELF_ATTENTION: false
TRAIN:
  BATCH_SIZE: 32
  LR: 0.001
  N_EPOCHS: 200
  N_NEG_PAIRS: 5000
  N_POINTS: 2048
  N_POS_PAIRS: 1000
  OPTIMIZER: adam
  SCHEDULER: cos
  TEMP: 0.007
